const { z } = require('zod');

// Schema for choices inside generated campaign nodes
const campaignChoiceSchema = z.object({
  id: z.string().default(() => `c_${Math.random().toString(36).substring(2, 7)}`),
  label: z.string().min(1),
  actionType: z.string().default('explore'),
  consequenceHint: z.string().optional()
});

// Schema for story nodes within generated campaign
const campaignNodeSchema = z.object({
  nodeId: z.string().default(() => `node_${Math.random().toString(36).substring(2, 7)}`),
  title: z.string().min(1),
  narrative: z.string().min(1),
  location: z.string().default('Lokasi Misterius'),
  backgroundId: z.string().default('bg_02_dungeon'),
  choices: z.array(campaignChoiceSchema).min(1),
  combatEncounter: z.object({
    enemyName: z.string(),
    hp: z.number().int().positive(),
    ac: z.number().int().positive(),
    attackBonus: z.number().int().default(2),
    damage: z.string().default('1d6+1')
  }).nullable().optional()
});

// Schema for preset enemies
const presetEnemySchema = z.object({
  name: z.string().min(1),
  hp: z.number().int().positive(),
  ac: z.number().int().positive(),
  attackBonus: z.number().int().default(2),
  damage: z.string().default('1d6+1'),
  cr: z.union([z.number(), z.string()]).default(1)
});

// Schema for custom campaign generated by Gemini / Fallback
const customCampaignSchema = z.object({
  id: z.string().default(() => `camp_custom_${Math.random().toString(36).substring(2, 9)}`),
  title: z.string().min(1),
  premise: z.string().min(1),
  theme: z.string().default('Gothic Dungeon'),
  difficulty: z.string().default('normal'),
  nodesCount: z.number().int().default(1),
  previewSummary: z.string().min(1),
  nodes: z.array(campaignNodeSchema).min(1),
  presetEnemies: z.array(presetEnemySchema).default([])
});

// Schema for dynamic NPC generation
const dynamicNpcSchema = z.object({
  id: z.string().default(() => `npc_gen_${Math.random().toString(36).substring(2, 7)}`),
  name: z.string().min(1),
  race: z.string().default('Human'),
  role: z.string().default('adventurer'),
  alignment: z.string().default('neutral'),
  greeting: z.string().min(1),
  personalityTraits: z.string().default('Tenang dan bijaksana'),
  inventory: z.array(z.object({
    itemId: z.string(),
    name: z.string().optional(),
    price: z.number().int().nonnegative().default(10)
  })).default([])
});

module.exports = {
  campaignChoiceSchema,
  campaignNodeSchema,
  presetEnemySchema,
  customCampaignSchema,
  dynamicNpcSchema
};
