const Campaign = require('../Campaign');

const campaignsData = [
  {
    id: 'whispering_tavern',
    title: 'Misteri Kedai Whispering Tavern',
    genre: 'dark_fantasy',
    threatLevel: 'Tier 1 (Level 1-3)',
    recommendedClasses: ['warrior', 'rogue', 'bard'],
    primarySkill: 'Persepsi & Investigasi',
    defaultBackgroundId: 'bg_01_tavern',
    defaultNpcId: 'char_npc_01_barkeep',
    icon: '🍺',
    coverImage: '/assets/backgrounds/bg_01_tavern.png',
    factions: ['Serikat Kedai Oakhaven', 'Guild Pencuri Bayangan'],
    premise: 'Keganjilan terjadi di ruang bawah tanah kedai Whispering Tavern, desa Oakhaven. Ketukan berulang terdengar dari balik tumpukan tong anggur selama tiga malam berturut-turut. Lokasi ini diduga terhubung dengan katakombe kuno yang terkubur di bawah permukiman.',
    introDialogue: 'Eldrin sang pemilik kedai meletakkan cangkir ke meja lalu berbisik pelan. "Ketukan itu makin sering terdengar tiap malam," ujarnya sambil menunjuk ke pintu lorong bawah tanah yang dipalang kayu. "Aku butuh bantuanmu sebelum situasi memburuk."'
  },
  {
    id: 'crypt_of_crimson',
    title: 'Makam Merah Darah & Teror Bayangan',
    genre: 'gothic_horror',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['cleric', 'paladin', 'wizard'],
    primarySkill: 'Arcana & Religi',
    defaultBackgroundId: 'bg_04_crimson_crypt',
    defaultNpcId: 'char_npc_02_informant',
    icon: '💀',
    coverImage: '/assets/backgrounds/bg_04_crimson_crypt.png',
    factions: ['Ordo Ksatria Matahari', 'Kultus Kematian Merah'],
    premise: 'Segel makam bangsawan kuno pecah setelah dirusak penjarah makam. Aktivitas pemanggilan arwah dan penjaga kerangka terdeteksi di sekitar altar, mengancam permukiman di lembah bawah.',
    introDialogue: 'Kabut tipis menyapu lantai batu basah saat sosok informan bertudung menemuimu di balik pilar. "Patroli kerangka penjaga sudah mulai aktif di koridor depan," bisiknya singkat. "Kita harus masuk sebelum mereka menyelesaikan ritual."'
  },
  {
    id: 'abyssal_citadel',
    title: 'Reruntuhan Samudra Sunken Citadel',
    genre: 'eldritch_mystery',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['mage', 'ranger', 'warlock'],
    primarySkill: 'Arcana & Daya Tahan (CON)',
    defaultBackgroundId: 'bg_03_sunken_citadel',
    defaultNpcId: 'char_npc_08_cultist',
    icon: '🌊',
    coverImage: '/assets/backgrounds/bg_03_sunken_citadel.png',
    factions: ['Penjaga Lautan Lepas', 'Pemuja Dagon Kedalaman'],
    premise: 'Sebuah kuil kuno yang tenggelam di palung laut memancarkan anomali energi psionik yang membingungkan kapal pelaut. Dinding kuil dipenuhi relief purba dan dijaga kultis yang menjaga rahasia gerbang laut.',
    introDialogue: 'Pendar hijau anemon menerangi pilar pualam di dasar laut berkubah udara. Seorang kultis berjubah basah menoleh ke arahmu, memegang belati berkarat dengan tatapan waspada saat kamu mendekat.'
  },
  {
    id: 'vampire_castle_shadows',
    title: 'Tahta Darah Kastil Bloodmere',
    genre: 'gothic_horror',
    threatLevel: 'Tier 3 (Level 6-8)',
    recommendedClasses: ['paladin', 'cleric', 'ranger'],
    primarySkill: 'Atletik (STR) & Karisma (CHA)',
    defaultBackgroundId: 'bg_05_vampire_castle',
    defaultNpcId: 'char_npc_03_vampire',
    icon: '🍷',
    coverImage: '/assets/backgrounds/bg_05_vampire_castle.png',
    factions: ['Klan Vampir Bloodmere', 'Pemburu Monster Salib Perak'],
    premise: 'Kastil Bloodmere di atas tebing karang dikuasai oleh Lord Cassian, bangsawan vampir yang mengisolasi wilayah ini. Beberapa pemuda desa dilaporkan menghilang, dan petunjuk mengarah langsung ke aula dalam kastil.',
    introDialogue: 'Pintu gerbang berderit berat saat angin dingin menerobos aula utama. Di ujung karpet beludru, sosok Lord Cassian duduk santai di kursinya sambil menatapmu dingin. "Tamu yang bernyali besar. Katakan tujuanmu kemari."'
  },
  {
    id: 'cursed_woods_dryad',
    title: 'Kutukan Rimba Hitam Sylvanis',
    genre: 'dark_fantasy',
    threatLevel: 'Tier 1 (Level 1-3)',
    recommendedClasses: ['ranger', 'druid', 'rogue'],
    primarySkill: 'Survival & Nature',
    defaultBackgroundId: 'bg_02_cursed_woods',
    defaultNpcId: 'char_npc_05_dryad',
    icon: '🌲',
    coverImage: '/assets/backgrounds/bg_02_cursed_woods.png',
    factions: ['Lingkaran Druid Hutan', 'Bandit Bayangan Hitam'],
    premise: 'Pohon-pohon di hutan tertua benua Aether mulai mengeluarkan getah hitam beracun. Satwa liar menjadi agresif dan tidak terkendali akibat pecahan kristal kelam yang tertanam di jantung hutan.',
    introDialogue: 'Ranting kering berderak pelan di bawah langkahmu. Sesosok peri pohon, Sylvanis, muncul dari balik batang ek besar dengan raut cemas. "Getah beracun itu mendekati sumber air desa. Kita tidak punya banyak waktu."'
  },
  {
    id: 'alchemy_lab_disaster',
    title: 'Bencana Asap Hijau Laboratorium Alkemis',
    genre: 'arcane_mystery',
    threatLevel: 'Tier 1 (Level 1-3)',
    recommendedClasses: ['mage', 'rogue', 'artificer'],
    primarySkill: 'Arcana & Sleight of Hand',
    defaultBackgroundId: 'bg_06_alchemy_lab',
    defaultNpcId: 'char_npc_06_goblin',
    icon: '🧪',
    coverImage: '/assets/backgrounds/bg_06_alchemy_lab.png',
    factions: ['Serikat Alkemis Kerajaan', 'Penyelundup Bahan Terlarang'],
    premise: 'Eksperimen transmutasi zat di laboratorium Paracelsus meledak, memenuhi ruangan dengan kabut asap hijau beracun. Peralatan mekanik di dalamnya mulai bereaksi tidak stabil dan mengancam menara.',
    introDialogue: 'Bau belerang menusuk hidung saat kamu melangkah melewati pecahan tabung kaca. Di balik meja tembaga, seorang goblin pedagang bahan kimia melambaikan tangan dengan panik. "Tungku utama mendidih! Katupnya harus segera ditutup!"'
  },
  {
    id: 'smuggler_cave_rebellion',
    title: 'Persekongkolan Rahasia Gua Penyelundup',
    genre: 'low_fantasy',
    threatLevel: 'Tier 1 (Level 1-3)',
    recommendedClasses: ['rogue', 'fighter', 'bard'],
    primarySkill: 'Stealth & Wawasan (WIS)',
    defaultBackgroundId: 'bg_07_smuggler_cave',
    defaultNpcId: 'char_npc_07_guard',
    icon: '⚓',
    coverImage: '/assets/backgrounds/bg_07_smuggler_cave.png',
    factions: ['Sindikat Penyelundup Karang', 'Garnisun Pelabuhan'],
    premise: 'Di celah gua karang pasang-surut, sindikat lokal menyelundupkan peti senjata tanpa izin dagang. Operasi ini diduga menjadi bagian dari rencana perlawanan bersenjata terhadap perwakilan penguasa pelabuhan.',
    introDialogue: 'Suara deburan ombak memantul di dinding gua basah. Di depan deretan peti kayu tersegel, seorang pengawal garnisun yang sedang menyamar menoleh ke arahmu. "Dua penjaga dermaga sedang lengah di ujung sana. Ini celah terbaik kita."'
  },
  {
    id: 'arcane_library_incursion',
    title: 'Teror Lembaran Terlarang Perpustakaan Bintang',
    genre: 'high_fantasy',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['wizard', 'cleric', 'monk'],
    primarySkill: 'Sejarah & Arcana',
    defaultBackgroundId: 'bg_08_arcane_library',
    defaultNpcId: 'char_hero_03_wizard',
    icon: '📚',
    coverImage: '/assets/backgrounds/bg_08_arcane_library.png',
    factions: ['Pustakawan Bintang Agung', 'Kolektor Grimoire Hitam'],
    premise: 'Perpustakaan agung mengalami gangguan medan sihir setelah sebuah kitab terlarang dibuka paksa. Beberapa naskah mantra purba terlepas dari lemari besi dan energi magis liar berputar di aula utama.',
    introDialogue: 'Perkamen bertulisan huruf biru melayang tak beraturan di antara rak-rak tinggi. Seorang pustakawan berjubah bintang memberi isyarat agar kamu merunduk. "Kitab di podium tengah masih terbuka. Segelnya harus kita pasang ulang."'
  },
  {
    id: 'dragon_crater_summit',
    title: 'Amarah Kawah Puncak Naga Vermithrax',
    genre: 'epic_fantasy',
    threatLevel: 'Tier 4 (Level 9+)',
    recommendedClasses: ['paladin', 'barbarian', 'warlock'],
    primarySkill: 'Atletik (STR) & Refleks (DEX)',
    defaultBackgroundId: 'bg_09_dragon_crater',
    defaultNpcId: 'char_hero_08_dragonborn',
    icon: '🌋',
    coverImage: '/assets/backgrounds/bg_09_dragon_crater.png',
    factions: ['Klan Pemburu Naga Gunung Api', 'Penyembah Naga Merah'],
    premise: 'Naga Vermithrax bangun di sarang kawah gunung berapi aktif Ignis Peak. Aktivitas magma meningkat drastis, mengancam permukiman di kaki bukit bila jalur aliran lahar tidak segera dialihkan atau ditenangkan.',
    introDialogue: 'Hawa panas menyengat menerpa wajahmu saat tiba di pinggir kaldera. Prajurit Dragonborn Ignis menunjuk ke arah celah batuan vulkanik di depan. "Vermithrax bertengger di atas kubah utama. Kita harus mendekat lewat dinding batu barat."'
  },
  {
    id: 'underdark_crystal_echoes',
    title: 'Gema Kristal Kegelapan Underdark',
    genre: 'subterranean_survival',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['ranger', 'rogue', 'dwarf'],
    primarySkill: 'Survival & Persepsi',
    defaultBackgroundId: 'bg_12_underdark_cavern',
    defaultNpcId: 'char_hero_04_dwarf',
    icon: '🍄',
    coverImage: '/assets/backgrounds/bg_12_underdark_cavern.png',
    factions: ['Kurcaci Tambang Bawah Tanah', 'Bangsa Drow Bayangan'],
    premise: 'Sebuah tim tambang kurcaci hilang kontak setelah menembus urat kristal safir di kedalaman Underdark. Suara desis dan guncangan tanah dilaporkan terjadi di sekitar lorong tambang nomor empat.',
    introDialogue: 'Pendar jamur biru menampakkan bekas gerobak tambang yang terbalik di persimpangan rel. Torin sang kurcaci memeriksa bekas cakaran pada tiang penyangga kayu. "Bukan runtuh biasa. Sesuatu menarik tim tambang ke lorong bawah."'
  },
  {
    id: 'frost_peak_survival',
    title: 'Badai Es Abadi Puncak Frost Peak',
    genre: 'survival_fantasy',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['barbarian', 'ranger', 'paladin'],
    primarySkill: 'Konstitusi (CON) & Survival',
    defaultBackgroundId: 'bg_14_frost_peak',
    defaultNpcId: 'char_hero_02_ranger',
    icon: '❄️',
    coverImage: '/assets/backgrounds/bg_14_frost_peak.png',
    factions: ['Suku Pengembara Badai Salju', 'Penjaga Menara Es'],
    premise: 'Badai es berkepanjangan melanda pos penjagaan Frost Peak, memutus jalur logistik pengembara gunung. Suar darurat sempat dinyalakan dari pondok pengungsian di dekat tebing es.',
    introDialogue: 'Angin gunung berhembus kencang menerbangkan serpihan salju tebal. Lyra sang pemandu rimba menunjuk ke arah pondok batu di lereng curam. "Pintu pondok tertimbun salju longsor. Kita harus membukanya sebelum suhu makin anjlok."'
  },
  {
    id: 'swamp_witch_coven',
    title: 'Misteri Pondok Nenek Sihir Rawa Hitam',
    genre: 'dark_fantasy',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['warlock', 'cleric', 'druid'],
    primarySkill: 'Arcana & Religi',
    defaultBackgroundId: 'bg_16_swamp_huts',
    defaultNpcId: 'char_npc_05_dryad',
    icon: '🐊',
    coverImage: '/assets/backgrounds/bg_16_swamp_huts.png',
    factions: ['Perserikatan Nenek Sihir Rawa', 'Penduduk Desa Tepi Danau'],
    premise: 'Pondok terpencil di pedalaman rawa air payau dicurigai menjadi sumber ramuan beracun yang meracuni sumur desa. Warga setempat meminta penyelidik memastikan kondisi di sekitar pondok panggung.',
    introDialogue: 'Air rawa kecokelatan memantulkan cahaya lentera temaram di ujung dermaga lapuk. Pintu pondok tampak sedikit renggang dan asap herbal tipis keluar dari jendela samping.'
  },
  {
    id: 'feywild_twilight_glade',
    title: 'Pesona Terlarang Padang Peri Feywild',
    genre: 'whimsical_mystery',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['bard', 'sorcerer', 'rogue'],
    primarySkill: 'Karisma (CHA) & Wawasan',
    defaultBackgroundId: 'bg_24_feywild_glade',
    defaultNpcId: 'char_hero_09_bard',
    icon: '🦋',
    coverImage: '/assets/backgrounds/bg_24_feywild_glade.png',
    factions: ['Istana Musim Semi Peri', 'Pengadilan Malam Fey'],
    premise: 'Sebuah lingkaran batu kuno di perbukitan membuka celah menuju padang Feywild. Dua pelancong yang tersesat belum kembali sejak kemarin sore, diduga terperangkap dalam lingkaran ilusi waktu peri.',
    introDialogue: 'Pendar cahaya keemasan menyelimuti padang rumput beraroma bunga liar. Seorang penyair pengelana duduk di atas batu bulat sambil mengamati batas kabut. "Mereka berjalan ke arah pohon kembar tadi pagi, tapi jejaknya berputar di tempat."'
  },
  {
    id: 'abandoned_cathedral_knights',
    title: 'Ratapan Ksatria Hantu Katedral Terbengkalai',
    genre: 'gothic_horror',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['paladin', 'cleric', 'fighter'],
    primarySkill: 'Sejarah & Religi',
    defaultBackgroundId: 'bg_25_abandoned_cathedral',
    defaultNpcId: 'char_hero_01_paladin',
    icon: '⛪',
    coverImage: '/assets/backgrounds/bg_25_abandoned_cathedral.png',
    factions: ['Arwah Ordo Perisai Putih', 'Kultus Pengkhianat'],
    premise: 'Sebuah katedral tua di pinggir kota tua menunjukkan aktivitas ganjil saat tengah malam. Suara dentang lonceng yang retak dan kilatan cahaya di balik kaca patri mengkhawatirkan penduduk sekitar.',
    introDialogue: 'Cahaya bulan masuk menembus atap katedral yang runtuh sebagian. Rekan ksatriamu mengangkat obor, menunjuk ke arah jejak kaki di lantai berdebu menuju ruang bawah tanah. "Seseorang baru saja lewat sini beberapa menit lalu."'
  },
  {
    id: 'clockwork_vault_heist',
    title: 'Pembobolan Brankas Mekanik Kuno',
    genre: 'steampunk_fantasy',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['rogue', 'artificer', 'wizard'],
    primarySkill: 'Investigasi & Ketangkasan (DEX)',
    defaultBackgroundId: 'bg_26_clockwork_vault',
    defaultNpcId: 'char_hero_05_rogue',
    icon: '⚙️',
    coverImage: '/assets/backgrounds/bg_26_clockwork_vault.png',
    factions: ['Perkumpulan Mekanik Kuno', 'Sindikat Pembobol Brankas'],
    premise: 'Sistem penguncian mekanik pada brankas kuno bank kota mengalami malfungsi dan terkunci otomatis dengan alarm aktif. Tim spesialis dipanggil untuk membuka mekanisme pengaman sebelum roda gigi internal rusak permanen.',
    introDialogue: 'Suara putaran roda gigi kuningan dan desis pipa uap memenuhi koridor bawah tanah. Rekanmu menyinari panel kunci kombinasi bernomor romawi. "Tiga silinder pertama macet. Kita harus mengatur ulang tuas di dinding samping lebih dulu."'
  },
  {
    id: 'goblin_war_siege',
    title: 'Pengepungan Garang Benteng Goblin',
    genre: 'tactical_action',
    threatLevel: 'Tier 1 (Level 1-3)',
    recommendedClasses: ['fighter', 'ranger', 'barbarian'],
    primarySkill: 'Taktik Militer & Atletik',
    defaultBackgroundId: 'bg_21_goblin_war_camp',
    defaultNpcId: 'char_npc_06_goblin',
    icon: '🏹',
    coverImage: '/assets/backgrounds/bg_21_goblin_war_camp.png',
    factions: ['Garnisun Perbatasan Kerajaan', 'Gerombolan Suku Taring Merah'],
    premise: 'Sekelompok goblin memasang barikade kayu runcing di jalur perlintasan pedagang pegunungan. Akses jalan tertutup dan pos penjagaan membutuhkan tim taktis untuk menembus pertahanan mereka.',
    introDialogue: 'Kepulan asap dari perkemahan terlihat jelas di balik pagar kayu runcing. Dari semak-semak perbatasan, seorang pramuka memberi kode tangan ke arah gerbang samping yang dijaga longgar.'
  },
  {
    id: 'singing_crystal_mines',
    title: 'Misteri Suara Resonansi Tambang Safir',
    genre: 'mystery_adventure',
    threatLevel: 'Tier 2 (Level 3-5)',
    recommendedClasses: ['bard', 'wizard', 'cleric'],
    primarySkill: 'Arcana & Konsentrasi (WIS)',
    defaultBackgroundId: 'bg_22_crystal_mines',
    defaultNpcId: 'char_hero_04_dwarf',
    icon: '💎',
    coverImage: '/assets/backgrounds/bg_22_crystal_mines.png',
    factions: ['Serikat Tambang Permata', 'Peneliti Arkanum Kristal'],
    premise: 'Urat kristal di sektor terdalam tambang safir memancarkan getaran resonansi berfrekuensi tinggi yang menyebabkan disorientasi para pekerja tambang. Serikat Tambang meminta penyelidik memeriksa sumber resonansi di gua kristal sebelum penambangan dihentikan.',
    introDialogue: 'Pendar biru dari kristal dinding memantulkan bayangan lorong yang sunyi. Mandor tambang menyerahkan penutup telinga lilin kepadamu. "Getaran dengungan itu semakin tajam melewati celah terowongan depan. Jangan berlama-lama di dekat urat utama."'
  },
  {
    id: 'torture_chamber_escape',
    title: 'Pelarian dari Penjara Bawah Tanah',
    genre: 'gritty_survival',
    threatLevel: 'Tier 1 (Level 1-3)',
    recommendedClasses: ['rogue', 'barbarian', 'monk'],
    primarySkill: 'Sleight of Hand & Daya Tahan (CON)',
    defaultBackgroundId: 'bg_23_dungeon_torture_chamber',
    defaultNpcId: 'char_npc_02_informant',
    icon: '⛓️',
    coverImage: '/assets/backgrounds/bg_23_dungeon_torture_chamber.png',
    factions: ['Inkuisisi Kerajaan Hitam', 'Tahanan Pemberontak'],
    premise: 'Ditahan tanpa senjata di sel bawah tanah benteng inkuisisi, tahanan harus memanfaatkan kelengahan penjaga, mencari peralatan darurat, dan menemukan jalur keluar melalui terowongan drainase benteng.',
    introDialogue: 'Lentera minyak di koridor luar berkedip pelan menyinari jeruji besi. Suara langkah penjaga yang berganti giliran terdengar menjauh dari blok tahanan. Kunci gembok sel berada di atas meja jaga beberapa meter di depan.'
  },
  {
    id: 'shadowfell_citadel_despair',
    title: 'Benteng Perbatasan Alam Shadowfell',
    genre: 'dark_fantasy',
    threatLevel: 'Tier 3 (Level 6-8)',
    recommendedClasses: ['paladin', 'cleric', 'warlock'],
    primarySkill: 'Keteguhan Hati (WIS) & Karisma',
    defaultBackgroundId: 'bg_19_shadowfell_citadel',
    defaultNpcId: 'char_hero_07_warlock',
    icon: '🌑',
    coverImage: '/assets/backgrounds/bg_19_shadowfell_citadel.png',
    factions: ['Pengawal Bayangan Hampa', 'Jiwa Tersesat Tanpa Raga'],
    premise: 'Retakan dimensional di benteng tua menarik sebagian wilayah perbatasan ke alam bayangan Shadowfell. Cahaya lentera jiwa di menara pengawas utama harus dinyalakan kembali untuk menstabilkan penghalang batas antar-alam.',
    introDialogue: 'Kabut abu-abu monokromatik menyelimuti serambi benteng batu yang dingin. Rekan pengawamu menyiapkan obor arkanum sambil menatap tangga menara. "Penghalang dimensi semakin rapuh. Kita harus mencapai puncak menara sebelum kabut menutup jalan."'
  },
  {
    id: 'abyssal_rift_endgame',
    title: 'Pertarungan Retakan Kosmik Abyssal Rift',
    genre: 'cosmic_horror',
    threatLevel: 'Tier 4 (Level 9+)',
    recommendedClasses: ['wizard', 'paladin', 'warlock', 'cleric'],
    primarySkill: 'Arcana & Daya Tahan Kosmik',
    defaultBackgroundId: 'bg_29_abyssal_rift',
    defaultNpcId: 'char_npc_09_lich',
    icon: '🌌',
    coverImage: '/assets/backgrounds/bg_29_abyssal_rift.png',
    factions: ['Aliansi Pahlawan Penjaga Dimensi', 'Entitas Kehampaan Kosmik'],
    premise: 'Retakan ruang terbuka di batas dataran tinggi Aether, memicu ketidakstabilan gravitasi dan ancaman invasi entitas kekosongan kosmik. Dewan penyihir dan ksatria mengutus regu elit untuk menyegel retakan inti menggunakan kristal penahan.',
    introDialogue: 'Gumpalan energi ungu berputar perlahan di atas jurang retakan terbuka di bibir tebing. Komandan regu memberi isyarat formasi bertahan saat kristal penyegel mulai bergetar. "Penyegelan dimulai sekarang. Jaga posisi barikade."'
  }
];

async function seedCampaigns() {
  for (const c of campaignsData) {
    await Campaign.upsert(c);
  }
  console.log(`[CampaignSeeder] Successfully synced ${campaignsData.length} master campaigns.`);
}

module.exports = { seedCampaigns, campaignsData };
